name: Build
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        love_version: ['11.5']
    steps:
    - uses: actions/checkout@v4.1.7
    - uses: mconnat/love-build@master
      id: love-build
      with:
        app_name: 'yasg'
        love_version: ${{ matrix.love_version }}
        source_dir: '.'
        result_dir: 'builds'
    # Upload the resulting artifacts
    - uses: actions/upload-artifact@v4
      with:
        name: macos-build
        path: ${{ steps.love-build.outputs.macos-filename }}
    - uses: actions/upload-artifact@v4
      with:
        name: win32-build
        path: ${{ steps.love-build.outputs.win32-filename }}
    - uses: actions/upload-artifact@v4
      with:
        name: win64-build
        path: ${{ steps.love-build.outputs.win64-filename }}
    - uses: actions/upload-artifact@v4
      with:
        name: love-build
        path: ${{ steps.love-build.outputs.love-filename }}
    - uses: actions/upload-artifact@v4
      with:
        name: web-build
        path: ${{ steps.love-build.outputs.web-filename }}
